### ISSUE TITLE
Annának

### ISSUE THREAD

**Issue by putrik981** [anna871-coder/anna871-coder.github.io#1]
Szia Anna,

Nagyon szép a kódod és örülök, hogy hasznosan töltöd a szabadidőd, méghozzá az informatika világában.
A readme mindig a legfontosabb. Abba írj bele mindent nagyon részletesen, hogy miről szól a kódod!

Üdv,
Fiad

**Comment by anna871-coder** [comment]
Szia Fiam,

És még te nem tudsz semmit a Git-ről.
Köszönöm a támogatásodat, jól esik.

Üdv:
Anyád

**Comment by anna871-coder** [comment]
Fiam jótanácsait megfogadom.
